#SPDX-License-Identifier: MIT-0
---
# vars file for mysql
MYSQL_HOST: "localhost"

#ROOT USER
MYSQL_ROOT_NAME: "root"
MYSQL_ROOT_LOGIN: "root"
MYSQL_ROOT_PASSWORD: "Liora2026!"

#PRESTASHOP DB
MYSQL_DB_NAME: "prestashop-db"


#PRESTASHOP USER
MYSQL_WEB_USER_NAME: "prestashop"
MYSQL_WEB_USER_LOGIN: "prestashop"
MYSQL_WEB_USER_PASSWORD: "LioraPrestashop2026!"