#SPDX-License-Identifier: MIT-0
---
# tasks file for mysql
  - name: Print OS family
    ansible.builtin.debug:
      msg: "OS Family: {{ ansible_facts['os_family'] }}"

  - name: Install MySQL server on Debian-based or Ubuntu-based systems
    ansible.builtin.apt:
      name: mysql-server
      state: present
    become: true
    when: ansible_facts['os_family'] == "Debian"

  - name: Install MySQL server on RedHat-based or CentOS-based systems
    ansible.builtin.yum:
      name: mysql-server
      state: present
    become: true
    when: ansible_facts['os_family'] == "RedHat"

  - name: Start and enable MySQL service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
    become: true

  - name: Set MySQL root password
    ansible.builtin.mysql_user:
      login_user: "{{ MYSQL_ROOT_LOGIN }}"
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      name: "{{ MYSQL_ROOT_NAME }}"
      password: "{{ MYSQL_ROOT_PASSWORD }}"
      host: "{{ MYSQL_HOST }}"
      state: present
    become: true

  - name: Remove anonymous MySQL users (to prevent access without password)
    ansible.builtin.mysql_user:
      login_user: "{{ MYSQL_ROOT_LOGIN }}"
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      name: ''
      host_all: true
      state: absent
    become: true

  - name: Remove test database
    ansible.builtin.mysql_db:
      login_user: "{{ MYSQL_ROOT_LOGIN }}"
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      name: test
      state: absent
    become: true

  - name: Create MySQL Prestashop database
    ansible.builtin.mysql_db:
      login_user: "{{ MYSQL_ROOT_LOGIN }}"
      login_password: "{{ MYSQL_ROOT_PASSWORD }}"
      name: "{{ MYSQL_DB_NAME }}"
      state: present
    become: true

  - name: Create MySQL Prestashop user
    ansible.builtin.mysql_user:
      name: "{{ MYSQL_WEB_USER_NAME }}"
      password: "{{ MYSQL_WEB_USER_PASSWORD }}"
      priv: "{{ MYSQL_DB_NAME }}.*:ALL"
      state: present
    become: true