pipeline {
environment { 
DOCKER_ID = "lachaizecode"
DOCKER_IMAGE = "fastapi-movie"
DOCKER_TAG = "v.${BUILD_ID}.0"
}
agent any

stages {
  stage('Docker Image Build'){
    steps {
      script {
      sh '''
        docker rm -f jenkins
        docker build -t $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG .
      sleep 6
      '''
      }
    }
  }

 stage('Docker Image Run'){ 
    steps {
      script {
      sh '''
      docker run -d -p 80:80 --name jenkins $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG
      sleep 10
      '''
      }
    }
  }
  stage('Test Container Response'){
    steps {
      script {
      sh '''
      curl localhost
      '''
      }
    }
  }
  stage('Docker Push To Hub'){
    environment
    {
      DOCKER_PASS = credentials("DOCKER_HUB_PASS")
    }
    steps {
      script {
        sh '''
        docker login -u $DOCKER_ID -p $DOCKER_PASS
        docker push $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG
        '''
      }
    }
  }
  stage('Dev Deployment'){
    environment {
    KUBECONFIG = credentials("config")
    }
    steps {
      script {
      sh '''
      rm -Rf ~/.kube/
      mkdir ~/.kube/
      ls
      cat $KUBECONFIG > ~/.kube/config
      cp fastapi/values.yaml values.yml
      cat values.yml
      sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml
      helm upgrade --install app fastapi --values=values.yml --namespace dev
      '''
      }
    }
  }
  stage('QA Deployment'){
    environment {
    KUBECONFIG = credentials("config")
    }
    steps {
      script {
      sh '''
      rm -Rf ~/.kube/
      mkdir ~/.kube/
      ls
      cat $KUBECONFIG > ~/.kube/config
      cp fastapi/values.yaml values.yml
      cat values.yml
      sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml
      helm upgrade --install app fastapi --values=values.yml --namespace qa
      '''
      }
    }
  }
  stage('Staging Deployment'){
    environment {
    KUBECONFIG = credentials("config")
    }
    steps {
      script {
      sh '''
      rm -Rf ~/.kube/
      mkdir ~/.kube/
      ls
      cat $KUBECONFIG > ~/.kube/config
      cp fastapi/values.yaml values.yml
      cat values.yml
      sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml
      helm upgrade --install app fastapi --values=values.yml --namespace staging
      '''
      }
    }
  }
  stage('Prod Deployment'){
    environment {
      KUBECONFIG = credentials("config")
      }
      steps {
        // Create an Approval Button for manual validation(15 min timeout).
        timeout(time: 15, unit: "MINUTES") {
          input message: 'Deploy in production ?', ok: 'Yes'
        }
        script {
          sh '''
          rm -Rf ~/.kube/
          mkdir ~/.kube/
          ls
          cat $KUBECONFIG > ~/.kube/config
          cp fastapi/values.yaml values.yml
          cat values.yml
          sed -i "s+tag.*+tag: ${DOCKER_TAG}+g" values.yml
          helm upgrade --install app fastapi --values=values.yml --namespace prod
          '''
        }
      }
    }
  }

}
