apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: "{{ .Values.castService.repository }}:{{ .Values.castService.tag }}"
          ports:
            - containerPort: 8000
