apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie
  labels:
    app: movie-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: "{{ .Values.movieService.repository }}:{{ .Values.movieService.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
