#SPDX-License-Identifier: MIT-0
---
# handlers file for prestashop
- name: Restart Apache Debian
  ansible.builtin.service:
    name: apache2
    state: restarted
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Restart Apache RedHat
  ansible.builtin.service:
    name: httpd
    state: restarted
  become: true
  when: ansible_facts['os_family'] == "RedHat"
